{"pytest_version": "8.3.4", "$report_type": "SessionStart"}
{"nodeid": "", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "test_aqa1/main_test.py", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "test_aqa1/pages", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "test_aqa1", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "test_results/allure-results", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "test_results", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": ".", "outcome": "passed", "longrepr": null, "result": null, "sections": [], "$report_type": "CollectReport"}
{"nodeid": "test_aqa1/main_test.py::test_open_page", "location": ["test_aqa1/main_test.py", 4, "test_open_page"], "keywords": {"test_open_page": 1, "allure_label": 1, "pytestmark": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c1299f550>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c1299f550>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, null]]}, "when": "setup", "user_properties": [], "sections": [], "duration": 20.527530770999874, "start": 1738764292.3667839, "stop": 1738764312.893286, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_open_page", "location": ["test_aqa1/main_test.py", 4, "test_open_page"], "keywords": {"test_open_page": 1, "allure_label": 1, "pytestmark": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.0005238170001575781, "start": 1738764312.9443157, "stop": 1738764312.9448423, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_go_to_services", "location": ["test_aqa1/main_test.py", 11, "test_go_to_services"], "keywords": {"test_go_to_services": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c12914d60>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c12914d60>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, null]]}, "when": "setup", "user_properties": [], "sections": [], "duration": 0.026282348000222555, "start": 1738764312.9463124, "stop": 1738764312.9725986, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_go_to_services", "location": ["test_aqa1/main_test.py", 11, "test_go_to_services"], "keywords": {"test_go_to_services": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.00044321399991531507, "start": 1738764312.9922328, "stop": 1738764312.9926777, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_go_to_cases", "location": ["test_aqa1/main_test.py", 17, "test_go_to_cases"], "keywords": {"test_go_to_cases": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c128ab340>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c128ab340>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, null]]}, "when": "setup", "user_properties": [], "sections": [], "duration": 0.026522055999976146, "start": 1738764312.993585, "stop": 1738764313.0201104, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_go_to_cases", "location": ["test_aqa1/main_test.py", 17, "test_go_to_cases"], "keywords": {"test_go_to_cases": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.0004159129998697608, "start": 1738764313.041359, "stop": 1738764313.0417764, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_go_to_reviews", "location": ["test_aqa1/main_test.py", 23, "test_go_to_reviews"], "keywords": {"test_go_to_reviews": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c128c8cd0>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c128c8cd0>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, null]]}, "when": "setup", "user_properties": [], "sections": [], "duration": 0.025460221999765054, "start": 1738764313.0426733, "stop": 1738764313.0681388, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_go_to_reviews", "location": ["test_aqa1/main_test.py", 23, "test_go_to_reviews"], "keywords": {"test_go_to_reviews": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.00041401399994356325, "start": 1738764313.092292, "stop": 1738764313.0927083, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_go_to_contacts", "location": ["test_aqa1/main_test.py", 29, "test_go_to_contacts"], "keywords": {"test_go_to_contacts": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c128c59a0>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @pytest.fixture", "    def driver():", "        chrome_options = Options()", "        if os.environ.get('CHROME_OPTIONS'):", "            for option in os.environ['CHROME_OPTIONS'].split():", "                chrome_options.add_argument(option)", "    ", ">       driver = webdriver.Chrome(options=chrome_options)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "test_aqa1/conftest.py", "lineno": 14, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    super().__init__("], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", "lineno": 45, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.service.start()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", "lineno": 55, "message": "in __init__"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    self.assert_process_still_running()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 113, "message": "in start"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def assert_process_still_running(self) -> None:", "        \"\"\"Check if the underlying process is still running.\"\"\"", "        return_code = self.process.poll()", "        if return_code:", ">           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")", "E           selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"], "reprfuncargs": {"args": [["self", "<selenium.webdriver.chrome.service.Service object at 0x7f6c128c59a0>"]]}, "reprlocals": null, "reprfileloc": {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "WebDriverException"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", "lineno": 126, "message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.cache/selenium/chromedriver/linux64/133.0.6943.53/chromedriver unexpectedly exited. Status code was: 127"}, null]]}, "when": "setup", "user_properties": [], "sections": [], "duration": 0.028248711999822262, "start": 1738764313.0935583, "stop": 1738764313.1218102, "$report_type": "TestReport"}
{"nodeid": "test_aqa1/main_test.py::test_go_to_contacts", "location": ["test_aqa1/main_test.py", 29, "test_go_to_contacts"], "keywords": {"test_go_to_contacts": 1, "main_test.py": 1, "test_aqa1": 1, "app": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.00045441499969456345, "start": 1738764313.154326, "stop": 1738764313.1547825, "$report_type": "TestReport"}
{"exitstatus": 1, "$report_type": "SessionFinish"}
